//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Busket
    {
        public int IdBusket { get; set; }
        public int IdUser { get; set; }
        public int IdProduct { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
